# Site settings
title: StatOfMind
header-img: img/galaxy.jpg
email: tlfvincent@gmail.com
description: "A melting pot of statistics, machine learning and data vizualization."
baseurl: ""
url: "http://tlfvincent.github.io/"
twitter_username: Thomas_LVincent
github_username:  tlfvincent

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
