title: StatOfMind
description: A melting pot of statistics, machine learning and data vizualization.

url: http://tlfvincent.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
#- title: Contact
#  url: /contact

social:
   github : tlfvincent
   twitter : Thomas_LVincent
   email: tlfvincent@gmail.com

